/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.isweishang.utils;

public final class R {
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_barColor=0x7f010001;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_barSpinCycleTime=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_barWidth=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_circleRadius=0x7f010006;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_fillRadius=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_linearProgress=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_progressIndeterminate=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_rimColor=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_rimWidth=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int matProg_spinSpeed=0x7f010004;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_alpha=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_centered=0x7f01000f;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_color=0x7f01000e;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_framerate=0x7f01000b;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_rippleDuration=0x7f01000c;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_ripplePadding=0x7f010011;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>simpleRipple</code></td><td>0</td><td></td></tr>
<tr><td><code>doubleRipple</code></td><td>1</td><td></td></tr>
<tr><td><code>rectangle</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int rv_type=0x7f010010;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_zoom=0x7f010012;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_zoomDuration=0x7f01000d;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int rv_zoomScale=0x7f010013;
    }
    public static final class color {
        /**  这个是活动中的颜色样式 
         */
        public static final int action_mult_live_shape=0x7f040007;
        public static final int black=0x7f04000e;
        public static final int blue=0x7f040010;
        public static final int blue_tran=0x7f040011;
        public static final int btn_selected=0x7f04000d;
        public static final int btn_stroke=0x7f04000c;
        public static final int colorAccent=0x7f04000b;
        public static final int colorPrimary=0x7f040009;
        public static final int colorPrimaryDark=0x7f04000a;
        public static final int download_btn_enable=0x7f040006;
        public static final int download_btn_normal=0x7f040004;
        public static final int download_btn_pressed=0x7f040005;
        public static final int feed_tag_color=0x7f040013;
        public static final int letv_color_b3000000=0x7f040000;
        public static final int letv_color_ff00a0e9=0x7f040003;
        public static final int letv_color_fff6f6f6=0x7f040002;
        public static final int letv_color_ffffffff=0x7f040001;
        public static final int letv_skin_vnew_controller_background=0x7f040008;
        public static final int rippelColor=0x7f040012;
        public static final int trans=0x7f04000f;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
        public static final int letv_skin_v4_ratetype_item_height=0x7f050003;
        public static final int letv_skin_v4_ratetype_item_width=0x7f050002;
        public static final int letv_skin_v4_volume_seekbar_height=0x7f050005;
        public static final int letv_skin_v4_volume_seekbar_width=0x7f050004;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int back_2x=0x7f020001;
        public static final int back_3x=0x7f020002;
        public static final int back_bg=0x7f020003;
        public static final int background=0x7f020004;
        public static final int btn_left_selected=0x7f020005;
        public static final int btn_middle_selected=0x7f020006;
        public static final int btn_right_selected=0x7f020007;
        public static final int button=0x7f020008;
        public static final int button_homepage=0x7f020009;
        public static final int choose_72=0x7f02000a;
        public static final int choose_no_72=0x7f02000b;
        public static final int explain=0x7f02000c;
        public static final int feed_back_title_back_drawable=0x7f02000d;
        public static final int feed_tag_drawable=0x7f02000e;
        public static final int home_btn_bg=0x7f02000f;
        public static final int ic_launcher=0x7f020010;
        public static final int input_box=0x7f020011;
        public static final int letv_skin_v4_back_btn_selecter=0x7f020012;
        public static final int letv_skin_v4_back_to_live=0x7f020013;
        public static final int letv_skin_v4_battery1=0x7f020014;
        public static final int letv_skin_v4_battery2=0x7f020015;
        public static final int letv_skin_v4_battery3=0x7f020016;
        public static final int letv_skin_v4_battery4=0x7f020017;
        public static final int letv_skin_v4_battery5=0x7f020018;
        public static final int letv_skin_v4_battery_charge=0x7f020019;
        public static final int letv_skin_v4_battery_selecter=0x7f02001a;
        public static final int letv_skin_v4_btn_back_default_white=0x7f02001b;
        public static final int letv_skin_v4_btn_back_focus=0x7f02001c;
        public static final int letv_skin_v4_btn_chgscreen_large=0x7f02001d;
        public static final int letv_skin_v4_btn_chgscreen_small=0x7f02001e;
        public static final int letv_skin_v4_btn_download=0x7f02001f;
        public static final int letv_skin_v4_btn_move=0x7f020020;
        public static final int letv_skin_v4_btn_pause=0x7f020021;
        public static final int letv_skin_v4_btn_play=0x7f020022;
        public static final int letv_skin_v4_btn_touch=0x7f020023;
        public static final int letv_skin_v4_download_btn_selector=0x7f020024;
        public static final int letv_skin_v4_forward=0x7f020025;
        public static final int letv_skin_v4_large_controller_ratetype_bg=0x7f020026;
        public static final int letv_skin_v4_large_gesture_brightness_icon=0x7f020027;
        public static final int letv_skin_v4_large_gesture_progress_vertical_style=0x7f020028;
        public static final int letv_skin_v4_large_gesture_seek_bg=0x7f020029;
        public static final int letv_skin_v4_large_gesture_volume_icon=0x7f02002a;
        public static final int letv_skin_v4_large_mult_live_action_jubao_3=0x7f02002b;
        public static final int letv_skin_v4_large_mult_live_action_jubao_back=0x7f02002c;
        public static final int letv_skin_v4_large_mult_live_action_jubaosuccess_3=0x7f02002d;
        public static final int letv_skin_v4_large_mult_live_action_list_onclick_style=0x7f02002e;
        public static final int letv_skin_v4_large_mult_live_action_lock=0x7f02002f;
        public static final int letv_skin_v4_large_mult_live_action_off=0x7f020030;
        public static final int letv_skin_v4_large_mult_live_action_on=0x7f020031;
        public static final int letv_skin_v4_large_mult_live_action_people=0x7f020032;
        public static final int letv_skin_v4_large_mult_live_action_querenjubao_3=0x7f020033;
        public static final int letv_skin_v4_large_mult_live_action_replay=0x7f020034;
        public static final int letv_skin_v4_large_mult_live_action_unlock=0x7f020035;
        public static final int letv_skin_v4_large_mult_live_action_v_1=0x7f020036;
        public static final int letv_skin_v4_large_mult_live_action_v_2=0x7f020037;
        public static final int letv_skin_v4_large_mult_live_logo_2=0x7f020038;
        public static final int letv_skin_v4_letv_iv_loading_image=0x7f020039;
        public static final int letv_skin_v4_line01=0x7f02003a;
        public static final int letv_skin_v4_line02=0x7f02003b;
        public static final int letv_skin_v4_line03=0x7f02003c;
        public static final int letv_skin_v4_line04=0x7f02003d;
        public static final int letv_skin_v4_line05=0x7f02003e;
        public static final int letv_skin_v4_line06=0x7f02003f;
        public static final int letv_skin_v4_line07=0x7f020040;
        public static final int letv_skin_v4_loading=0x7f020041;
        public static final int letv_skin_v4_logo=0x7f020042;
        public static final int letv_skin_v4_net_no=0x7f020043;
        public static final int letv_skin_v4_net_wifi=0x7f020044;
        public static final int letv_skin_v4_new_seek_bar_thumb=0x7f020045;
        public static final int letv_skin_v4_pano_cover=0x7f020046;
        public static final int letv_skin_v4_rewind=0x7f020047;
        public static final int letv_skin_v4_small_seek_bar_2_style=0x7f020048;
        public static final int letv_skin_v4_top_floatin_bg=0x7f020049;
        public static final int letv_skin_v4_wifi_selecter=0x7f02004a;
        public static final int play_btn_bg=0x7f02004b;
        public static final int radio_selector=0x7f02004c;
        public static final int textcolor_selector=0x7f02004d;
        public static final int tijiao_2x=0x7f02004e;
        public static final int tijiao_3x=0x7f02004f;
        public static final int title_back_drawable=0x7f020050;
        public static final int xuankaung_2x=0x7f020051;
        public static final int xuankaung_3x=0x7f020052;
        public static final int xuanze_2x=0x7f020053;
        public static final int xuanze_3x=0x7f020054;
    }
    public static final class id {
        public static final int active_content=0x7f080007;
        public static final int active_id=0x7f080006;
        public static final int active_player_hasSkin=0x7f080021;
        public static final int active_player_noSkin=0x7f080022;
        public static final int adtest=0x7f08007d;
        public static final int ass_layout=0x7f080029;
        public static final int back=0x7f08003a;
        public static final int btn1=0x7f08002b;
        public static final int btn2=0x7f08002c;
        public static final int btn_back=0x7f08003c;
        public static final int btn_cancel_inform=0x7f080059;
        public static final int btn_confirm_inform=0x7f080058;
        public static final int btn_error_replay=0x7f080061;
        public static final int btn_error_report=0x7f080062;
        public static final int btn_submit=0x7f080040;
        public static final int button1=0x7f08000b;
        public static final int check_group=0x7f08003d;
        public static final int console=0x7f08002e;
        public static final int container=0x7f08000c;
        public static final int delete1=0x7f080039;
        public static final int description=0x7f08001c;
        public static final int domain_content=0x7f080076;
        public static final int doubleRipple=0x7f080000;
        public static final int down_progress=0x7f080033;
        public static final int download1=0x7f080010;
        public static final int download2=0x7f080013;
        public static final int download3=0x7f080016;
        public static final int download_btn=0x7f08004a;
        public static final int download_list=0x7f080080;
        public static final int edit_feed_content=0x7f08003e;
        public static final int edit_phone=0x7f08003f;
        public static final int et_uu1=0x7f08000d;
        public static final int et_uu2=0x7f080011;
        public static final int et_uu3=0x7f080014;
        public static final int et_vu1=0x7f08000f;
        public static final int et_vu2=0x7f080012;
        public static final int et_vu3=0x7f080015;
        public static final int file_name=0x7f080034;
        public static final int floating_right_mutl_live_lay=0x7f08005e;
        public static final int full_back=0x7f080066;
        public static final int full_battery=0x7f08006a;
        public static final int full_net=0x7f080069;
        public static final int full_time=0x7f08006b;
        public static final int full_title=0x7f080067;
        public static final int head=0x7f08001a;
        public static final int hls=0x7f080079;
        public static final int iv_backgroud=0x7f080052;
        public static final int iv_video_inform=0x7f08006c;
        public static final int iv_video_lock=0x7f080068;
        public static final int jiwei=0x7f08005a;
        public static final int jiwei_lay=0x7f08005b;
        public static final int landscape_root=0x7f080019;
        public static final int letv_skin_loading=0x7f080049;
        public static final int letv_skin_v4_letv_iv_loading=0x7f080044;
        public static final int letv_skin_v4_letv_iv_loading_line=0x7f080045;
        public static final int letv_skin_v4_letv_ll_loading=0x7f080043;
        public static final int letv_skin_v4_letv_rl_loading=0x7f080042;
        public static final int list_view=0x7f080018;
        public static final int listview=0x7f080017;
        public static final int liveId=0x7f080072;
        public static final int live_ID=0x7f080075;
        public static final int live_hasSkin=0x7f08001f;
        public static final int live_noSkin=0x7f080020;
        public static final int live_path=0x7f08007a;
        public static final int mobile_player_hasSkin=0x7f080023;
        public static final int mobile_player_noSkin=0x7f080024;
        public static final int mutl_live_btn=0x7f08005f;
        public static final int mutl_live_lay=0x7f08005d;
        public static final int option_lay=0x7f08006e;
        public static final int other=0x7f080025;
        public static final int path_content=0x7f08007b;
        public static final int pause_resume_btn=0x7f080070;
        public static final int pb_loading=0x7f08005c;
        public static final int people_count=0x7f08006d;
        public static final int playPath=0x7f080074;
        public static final int play_local=0x7f080026;
        public static final int progress=0x7f08006f;
        public static final int progressBar=0x7f080053;
        public static final int progressBar1=0x7f080036;
        public static final int progress_time=0x7f080055;
        public static final int progress_time_duration=0x7f080057;
        public static final int progress_time_split=0x7f080056;
        public static final int progress_value=0x7f080035;
        public static final int progress_wheel=0x7f080041;
        public static final int radioGroup=0x7f080077;
        public static final int rectangle=0x7f080001;
        public static final int remove_btn=0x7f080071;
        public static final int root=0x7f080027;
        public static final int root_layout=0x7f080028;
        public static final int root_player=0x7f080009;
        public static final int rtmp=0x7f080078;
        public static final int scroll_view=0x7f08002d;
        public static final int sdk_title=0x7f08001b;
        public static final int seek_imageView=0x7f080054;
        public static final int simpleRipple=0x7f080002;
        public static final int skin_text_duration=0x7f080046;
        public static final int skin_txt_duration=0x7f080048;
        public static final int skin_txt_position=0x7f080047;
        public static final int startActive=0x7f080008;
        public static final int startDownload1=0x7f080037;
        public static final int startLive=0x7f080005;
        public static final int startMobileLive=0x7f08007c;
        public static final int startPlay1=0x7f080038;
        public static final int startVod=0x7f080087;
        public static final int streamId=0x7f080073;
        public static final int texture_view_tv=0x7f08000a;
        public static final int title=0x7f08003b;
        public static final int tv_error_code=0x7f080064;
        public static final int tv_error_feedback=0x7f080063;
        public static final int tv_error_message=0x7f080060;
        public static final int tv_error_msg=0x7f080065;
        public static final int two_player=0x7f08007f;
        public static final int uu_content1=0x7f080031;
        public static final int uuid_content=0x7f080004;
        public static final int ver=0x7f08002f;
        public static final int videoContainer=0x7f080030;
        public static final int video_list=0x7f08007e;
        public static final int videobody=0x7f08002a;
        public static final int vnew_change_mode=0x7f08004e;
        public static final int vnew_chg_btn=0x7f08004c;
        public static final int vnew_play_btn=0x7f08004b;
        public static final int vnew_rate_btn=0x7f08004d;
        public static final int vnew_seekbar=0x7f080050;
        public static final int vnew_text_duration_ref=0x7f08004f;
        public static final int vnew_time_text=0x7f080051;
        public static final int vodId=0x7f080081;
        public static final int vodPath=0x7f080082;
        public static final int vodPath_content=0x7f080086;
        public static final int vodTitle=0x7f080003;
        public static final int vod_hasSkin=0x7f08001d;
        public static final int vod_noSkin=0x7f08001e;
        public static final int vod_playPath=0x7f080085;
        public static final int vod_uuid=0x7f08000e;
        public static final int vod_vuid=0x7f080083;
        public static final int vu_content1=0x7f080032;
        public static final int vuid_content=0x7f080084;
    }
    public static final class layout {
        public static final int active_live=0x7f030000;
        public static final int active_play=0x7f030001;
        public static final int activity_ad_view_layout=0x7f030002;
        public static final int activity_download=0x7f030003;
        public static final int activity_list_view_layout=0x7f030004;
        public static final int activity_main=0x7f030005;
        public static final int activity_more_player_layout=0x7f030006;
        public static final int activity_play=0x7f030007;
        public static final int activity_play_no_skin=0x7f030008;
        public static final int download_list=0x7f030009;
        public static final int header=0x7f03000a;
        public static final int letv_feed_back_activity_layout=0x7f03000b;
        public static final int letv_skin_bonus_loading_layout=0x7f03000c;
        public static final int letv_skin_controller_text_timer=0x7f03000d;
        public static final int letv_skin_loading_layout=0x7f03000e;
        public static final int letv_skin_v4_back_to_live=0x7f03000f;
        public static final int letv_skin_v4_btn_chgscreen_layout=0x7f030010;
        public static final int letv_skin_v4_btn_play_layout=0x7f030011;
        public static final int letv_skin_v4_change_mode_button_layout=0x7f030012;
        public static final int letv_skin_v4_controller_large_layout=0x7f030013;
        public static final int letv_skin_v4_controller_large_live_layout=0x7f030014;
        public static final int letv_skin_v4_controller_layout=0x7f030015;
        public static final int letv_skin_v4_controller_live_layout=0x7f030016;
        public static final int letv_skin_v4_download_button_layout=0x7f030017;
        public static final int letv_skin_v4_large_gesture_brightness_layout=0x7f030018;
        public static final int letv_skin_v4_large_gesture_seek_layout=0x7f030019;
        public static final int letv_skin_v4_large_gesture_volume_layout=0x7f03001a;
        public static final int letv_skin_v4_large_mult_live_action_layout_inform_dialog=0x7f03001b;
        public static final int letv_skin_v4_large_mult_live_action_no_video_layout=0x7f03001c;
        public static final int letv_skin_v4_large_mult_live_action_sub_live_lay=0x7f03001d;
        public static final int letv_skin_v4_large_mult_live_layout=0x7f03001e;
        public static final int letv_skin_v4_notice_layout=0x7f03001f;
        public static final int letv_skin_v4_pano_cover_layout=0x7f030020;
        public static final int letv_skin_v4_ratetype_button_layout=0x7f030021;
        public static final int letv_skin_v4_ratetype_item=0x7f030022;
        public static final int letv_skin_v4_ratetype_layout=0x7f030023;
        public static final int letv_skin_v4_small_seekbar_layout=0x7f030024;
        public static final int letv_skin_v4_top_layout=0x7f030025;
        public static final int letv_skin_v4_top_mult_live_layout=0x7f030026;
        public static final int list_item_layout=0x7f030027;
        public static final int live=0x7f030028;
        public static final int mobile_live=0x7f030029;
        public static final int other=0x7f03002a;
        public static final int two_player_switch=0x7f03002b;
        public static final int vod=0x7f03002c;
    }
    public static final class string {
        public static final int activeId=0x7f06001a;
        public static final int active_live=0x7f06001b;
        public static final int active_player_hasSkin=0x7f060008;
        public static final int active_player_noSkin=0x7f060009;
        public static final int app_name=0x7f060000;
        public static final int description=0x7f06000d;
        public static final int domain=0x7f060012;
        public static final int download_list=0x7f06001f;
        public static final int hls=0x7f060016;
        public static final int home_title=0x7f060003;
        public static final int letv_network_message=0x7f060001;
        public static final int letv_notice_message=0x7f060002;
        public static final int liveId=0x7f06000f;
        public static final int live_ID=0x7f060020;
        public static final int live_hasSkin=0x7f060006;
        public static final int live_noSkin=0x7f060007;
        public static final int mobile_player_hasSkin=0x7f06000a;
        public static final int mobile_player_noSkin=0x7f06000b;
        public static final int other=0x7f06000c;
        public static final int playId=0x7f060017;
        public static final int play_Path=0x7f060011;
        public static final int pop_test=0x7f06001c;
        public static final int rtmp=0x7f060015;
        public static final int start_live=0x7f060013;
        public static final int start_vod=0x7f060014;
        public static final int streamId=0x7f060010;
        public static final int two_player=0x7f06001e;
        public static final int uuid=0x7f060018;
        public static final int versionCode=0x7f06000e;
        public static final int video_list=0x7f06001d;
        public static final int vod_hasSkin=0x7f060004;
        public static final int vod_noSkin=0x7f060005;
        public static final int vuid=0x7f060019;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
 Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
        public static final int BtnAttr=0x7f070002;
        public static final int downLinearLayout=0x7f070006;
        public static final int downbtn=0x7f07000a;
        public static final int playbtn=0x7f070009;
        public static final int radioButtonAtrr=0x7f070004;
        public static final int tabBtnAtrr=0x7f070003;
        public static final int vodEditText=0x7f070008;
        public static final int vodLinearLayout=0x7f070005;
        public static final int vodTextView=0x7f070007;
    }
    public static final class styleable {
        /** Attributes that can be used with a ProgressWheel.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_barColor com.lecloud.lecloudsdkdemo:matProg_barColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_barSpinCycleTime com.lecloud.lecloudsdkdemo:matProg_barSpinCycleTime}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_barWidth com.lecloud.lecloudsdkdemo:matProg_barWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_circleRadius com.lecloud.lecloudsdkdemo:matProg_circleRadius}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_fillRadius com.lecloud.lecloudsdkdemo:matProg_fillRadius}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_linearProgress com.lecloud.lecloudsdkdemo:matProg_linearProgress}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_progressIndeterminate com.lecloud.lecloudsdkdemo:matProg_progressIndeterminate}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_rimColor com.lecloud.lecloudsdkdemo:matProg_rimColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_rimWidth com.lecloud.lecloudsdkdemo:matProg_rimWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_matProg_spinSpeed com.lecloud.lecloudsdkdemo:matProg_spinSpeed}</code></td><td></td></tr>
           </table>
           @see #ProgressWheel_matProg_barColor
           @see #ProgressWheel_matProg_barSpinCycleTime
           @see #ProgressWheel_matProg_barWidth
           @see #ProgressWheel_matProg_circleRadius
           @see #ProgressWheel_matProg_fillRadius
           @see #ProgressWheel_matProg_linearProgress
           @see #ProgressWheel_matProg_progressIndeterminate
           @see #ProgressWheel_matProg_rimColor
           @see #ProgressWheel_matProg_rimWidth
           @see #ProgressWheel_matProg_spinSpeed
         */
        public static final int[] ProgressWheel = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009
        };
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_barColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_barColor
        */
        public static final int ProgressWheel_matProg_barColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_barSpinCycleTime}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_barSpinCycleTime
        */
        public static final int ProgressWheel_matProg_barSpinCycleTime = 5;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_barWidth}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_barWidth
        */
        public static final int ProgressWheel_matProg_barWidth = 8;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_circleRadius}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_circleRadius
        */
        public static final int ProgressWheel_matProg_circleRadius = 6;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_fillRadius}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_fillRadius
        */
        public static final int ProgressWheel_matProg_fillRadius = 7;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_linearProgress}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_linearProgress
        */
        public static final int ProgressWheel_matProg_linearProgress = 9;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_progressIndeterminate}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_progressIndeterminate
        */
        public static final int ProgressWheel_matProg_progressIndeterminate = 0;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_rimColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_rimColor
        */
        public static final int ProgressWheel_matProg_rimColor = 2;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_rimWidth}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_rimWidth
        */
        public static final int ProgressWheel_matProg_rimWidth = 3;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#matProg_spinSpeed}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:matProg_spinSpeed
        */
        public static final int ProgressWheel_matProg_spinSpeed = 4;
        /** Attributes that can be used with a RippleView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RippleView_rv_alpha com.lecloud.lecloudsdkdemo:rv_alpha}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_centered com.lecloud.lecloudsdkdemo:rv_centered}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_color com.lecloud.lecloudsdkdemo:rv_color}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_framerate com.lecloud.lecloudsdkdemo:rv_framerate}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_rippleDuration com.lecloud.lecloudsdkdemo:rv_rippleDuration}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_ripplePadding com.lecloud.lecloudsdkdemo:rv_ripplePadding}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_type com.lecloud.lecloudsdkdemo:rv_type}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_zoom com.lecloud.lecloudsdkdemo:rv_zoom}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_zoomDuration com.lecloud.lecloudsdkdemo:rv_zoomDuration}</code></td><td></td></tr>
           <tr><td><code>{@link #RippleView_rv_zoomScale com.lecloud.lecloudsdkdemo:rv_zoomScale}</code></td><td></td></tr>
           </table>
           @see #RippleView_rv_alpha
           @see #RippleView_rv_centered
           @see #RippleView_rv_color
           @see #RippleView_rv_framerate
           @see #RippleView_rv_rippleDuration
           @see #RippleView_rv_ripplePadding
           @see #RippleView_rv_type
           @see #RippleView_rv_zoom
           @see #RippleView_rv_zoomDuration
           @see #RippleView_rv_zoomScale
         */
        public static final int[] RippleView = {
            0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d,
            0x7f01000e, 0x7f01000f, 0x7f010010, 0x7f010011,
            0x7f010012, 0x7f010013
        };
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_alpha}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_alpha
        */
        public static final int RippleView_rv_alpha = 0;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_centered}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_centered
        */
        public static final int RippleView_rv_centered = 5;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_color}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_color
        */
        public static final int RippleView_rv_color = 4;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_framerate}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_framerate
        */
        public static final int RippleView_rv_framerate = 1;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_rippleDuration}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_rippleDuration
        */
        public static final int RippleView_rv_rippleDuration = 2;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_ripplePadding}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_ripplePadding
        */
        public static final int RippleView_rv_ripplePadding = 7;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_type}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>simpleRipple</code></td><td>0</td><td></td></tr>
<tr><td><code>doubleRipple</code></td><td>1</td><td></td></tr>
<tr><td><code>rectangle</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.lecloud.lecloudsdkdemo:rv_type
        */
        public static final int RippleView_rv_type = 6;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_zoom}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_zoom
        */
        public static final int RippleView_rv_zoom = 8;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_zoomDuration}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_zoomDuration
        */
        public static final int RippleView_rv_zoomDuration = 3;
        /**
          <p>This symbol is the offset where the {@link com.lecloud.lecloudsdkdemo.R.attr#rv_zoomScale}
          attribute's value can be found in the {@link #RippleView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.lecloud.lecloudsdkdemo:rv_zoomScale
        */
        public static final int RippleView_rv_zoomScale = 9;
    };
}
